export const frontendLocalDomain = "http://localhost:6969"
export const frontendLocalServeDomain = "http://localhost:80"
export const frontendDevelopmentDomain = ""
export const frontendProductionDomain = ""
export const backendDevelopmentDomain = ""
export const backendProductionDomain = ""
export const sharedRootDomainName = ""
